export default [
  {
    id: '12703',
    name: '定调',
    progress: 50,
    relevance: 0,
    type: '',
    description: '定调',
    code: '',
    level: 1,
    status: 'STATUS_ACTIVE',
    depends: '',
    canWrite: false,
    startIsMilestone: false,
    collapsed: true,
    assigs: [],
    hasChild: false,
    progressByWorklog: false,
    start: 1557849600000,
    end: 1558627200000,
    duration: 0
  },
  {
    id: '12357',
    name: '回插特效',
    progress: 20,
    relevance: 0,
    type: '',
    description: '回插特效',
    code: '',
    level: 1,
    status: 'STATUS_ACTIVE',
    depends: '',
    canWrite: false,
    startIsMilestone: false,
    collapsed: true,
    assigs: [],
    hasChild: false,
    progressByWorklog: false,
    start: 1558195200000,
    end: 1558800000000,
    duration: 0
  }
]
